# ModSecurity Configuration
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecAuditEngine RelevantOnly
SecAuditLog /var/log/modsec_audit.log
SecLogDir /var/log/

SecAuditLogParts ABIJDEFHZ

SecDefaultAction "phase:1,deny,log"
SecDefaultAction "phase:2,deny,status:403"

Include /etc/modsecurity/crs/owasp-modsecurity-crs/*.conf
