const END_POINTS = {
  HOME_INFORMATIVE_NOTES: 'attendance_user_id',
  HOME_SAUDE: 'absence_disease',
  HOME_FERIAS: 'absence_vacations',
  HOME_ANIVERSARIO: 'employees_birthday_month',
  HOME_ACTIVITY: 'activities',
  HOME_REQUEST: 'absence',
  HOME_DOCUMENT_REQUEST: 'document',
  HOME_TIME_OFF: 'total_absences',
  HOME_TYPE_REQUEST: 'reasons_absence',
  HOME_DOCUMENT_TYPE_REQUEST: 'doc_request_type',
  HOME_REQUEST_PENDENTE: 'pending_absences',
  HOME_REQUEST_PENDENTE_BY_ID: 'absence',
  HOME_REQUEST_DOCUMENT_PENDENTE_BY_ID: 'employee_requested_documents',
  HOME_REQUEST_CANCEL: 'change_status_absence',
  HOME_REQUEST_CHANGE_STATUS: 'change_status_absence',
  HOME_REQUEST_CHANGE_STATUS_SH: 'manager_status_change',
  HOME_REQUEST_CHANCE: 'update_absence',
  REQUEST_REVIEW: 'request_review',
  INFO_NOTES: 'info_notes',
  INFO_NOTE: 'info_note',
  HOME_REQUEST_EMPLOYEE_STATUS: 'pending_absences',
  DOCUMENT_REQUEST: 'documents',
}

export default END_POINTS
