
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443;

    index index.html;
    server_name localhost;

    ssl_certificate ../ssl/selfsigned.crt;
    ssl_certificate_key ../ssl/selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    # react app & front-end files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }

    # Logs específicos para este servidor
    access_log /var/log/nginx/app_sec.log;
    error_log /var/log/nginx/app_sec.log warn;

}
