# ModSecurity Core Rule Set setup
#
# Crs-setup.conf - Configuração padrão

# Escolha o nível de segurança do CRS:
# 1 - Proteção mínima (menos detecções falsas)
# 2 - Proteção média
# 3 - Proteção elevada
# 4 - Proteção paranoica (mais detecções falsas)
SecDefaultAction "phase:1,log,auditlog,pass"
SecDefaultAction "phase:2,log,auditlog,pass"
SecRuleEngine On

# Defina o nível de paranoia
# Quanto mais alto o nível, mais regras são aplicadas
SecAction \
 "id:900000, \
  phase:1, \
  nolog, \
  pass, \
  t:none, \
  setvar:tx.paranoia_level=1"

# Defina o tamanho máximo permitido do corpo da requisição
SecRequestBodyLimit 13107200

# Defina o tamanho máximo permitido do corpo da resposta
SecResponseBodyLimit 13107200
