# Basic Config for ModSecurity
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

# Logging settings
SecAuditLog /var/log/modsec_audit.log
SecAuditLogParts ABIFHZ

# Include OWASP Core Rule Set
Include /etc/nginx/modsec/crs-setup.conf
Include /etc/nginx/modsec/rules/*.conf
